[project]
name = "masevakansiemense"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "holidays>=0.74",
    "pyside6>=6.9.1",
]

[dependency-groups]
dev = [
    "cutie>=0.3.2",
    "rich>=14.0.0",
]
